import Head from "next/head";
import { Box, Heading, Text, SimpleGrid, Image, Container, Flex, Stack, Button } from '@chakra-ui/react';
import Navbar from "../components/navbar/index"
import Header from "../components/Header/index"
import Feature from "../components/Feature/index"
import Footer from "../components/Footer/index"

export default function Home() {
  return (
    <>
      <Head>
        <title>Theseus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Header/>
      <Feature/>
    <Box textAlign="center" py={10} mt={20} px={[4, 6, 8]} mx="auto" maxW="800px">
      <Heading
        as="h2"
        size="2xl"
        bgGradient="linear(to-r, green.400, green.600)"
        backgroundClip="text"
        mb={4}
      >
        OUR SERVICES
      </Heading>
      <Text fontSize={["16px", "18px", "20px"]} color="white" mb={4}>
        At Theseus, <Text as="span" fontWeight="bold">we make it easy to find the parts or repair services you need.</Text>
      </Text>
      <Text color="gray.500" mb={6} fontSize={["14px", "16px"]}>
        With technology, we collaborate with the best suppliers to ensure maximum quality in every reconditioned component. We ensure that all the components we provide are safe and efficient, keeping what matters most in full operation.
      </Text>
      <Button bg="#FCF5EB" size="lg">
              REACH US
            </Button>
    </Box>
    <Box bg="#FCF5EB" mt={10} p={8}>
      <Container>
        <Flex justifyContent="center">
          <SimpleGrid columns={[1, 2, 3, 4, 5]} spacing={4} alignItems="center">
            <Image src="./man.png" alt="Imagem 1" w="100%" h="auto" />
            <Image src="/daf.png" alt="Imagem 2" w="100%" h="auto" />
            <Image src="/volvo.png" alt="Imagem 3" w="100%" h="auto" />
            <Image src="/scania.png" alt="Imagem 4" w="100%" h="auto" />
            <Image src="/iveco.png" alt="Imagem 5" w="100%" h="auto" />
          </SimpleGrid>
        </Flex>
      </Container>
    </Box>
    <Box p={4} mt={10}>
      <Container maxW={'6xl'} mt={10}>
        <SimpleGrid columns={{ base: 1, md: 2 }} spacing={10}>
          <Stack spacing={4} as={Container} maxW={'3xl'} textAlign={'center'}>
            <Heading fontSize={'5xl'} color={'whitesmoke'}>
              For Those in Need of Parts!
            </Heading>
            <Text color={'white'} fontSize={'17'}>
              <Text as="span" fontWeight="bold">
                More Affordable Prices:
              </Text>{' '}
              In addition to high quality, our prices are more accessible, allowing you to save both time and money.
            </Text>
            <Text color={'white'} fontSize={'17'}>
              <Text as="span" fontWeight="bold">
                More Affordable Prices:
              </Text>{' '}
              In addition to high quality, our prices are more accessible, allowing you to save both time and money.
            </Text>
          </Stack>
          <Stack spacing={4} as={Container} maxW={'3xl'} textAlign={'center'}>
            <Heading fontSize={'5xl'} color={'white'}>
              If you are a repair partner!
            </Heading>
            <Text color={'white'} fontSize={'17'}>
              <Text as="span" fontWeight="bold">
                Market Access:
              </Text>{' '}
              Our platform connects you to a broad network of customers seeking repairs.
            </Text>
            <Text color={'white'} fontSize={'17'}>
              <Text as="span" fontWeight="bold">
                Trust and Traceability:
              </Text>{' '}
              We ensure that each case is traceable and of high quality.
            </Text>
          </Stack>
        </SimpleGrid>
        <Stack mt={10}>
        <Button bg="#FCF5EB" size="lg">
        KNOW MORE HERE
            </Button>
            </Stack>
      </Container>
    </Box>
    <Box p={4} bg={'#65676B'} color={'white'} textAlign={'center'} mt={10} >
  <Text mt={10} fontSize={['xl', '2xl', '3xl', '4xl']} fontWeight={'bold'}>
    Effortless Matchmaking
  </Text>
  <Text mb={10}  maxW={'650px'} mx={'auto'} mt={4}>
    Theseus simplifies the process of finding reliable repair services by connecting you with a network of skilled experts. Whether it's fixing a truck engine, repairing all kind of ECUs, or addressing quality issues, Theseus ensures that you're linked to the right expertise.
  </Text>
</Box>
<Button
        bg="#FCF5EB"
        color="green.800"
        size="lg"
        position="fixed"
        bottom="2rem"
        left="2rem"
        zIndex="999"
        display={{ base: 'block', md: 'none' }} // Exibir apenas em dispositivos móveis
        onClick={() => window.location.href = '/addpart'}
      >
        Publish Part Now
      </Button>

<Footer/>
   </>
  );
}
